
import React from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import HolidayForm from "./HolidayForm";
import { Holiday } from "@/types/holiday";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";
import { InfoIcon } from "lucide-react";

interface HolidayDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  holiday?: Holiday | null;
}

export const HolidayDialog: React.FC<HolidayDialogProps> = ({
  open,
  onOpenChange,
  holiday,
}) => {
  const isEditing = Boolean(holiday?.id);
  const isAutoGenerated = holiday?.autoGenerated || false;
  
  const handleCancel = () => {
    onOpenChange(false);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-lg">
        <DialogHeader className="flex flex-row items-center justify-between">
          <DialogTitle className="text-lg">
            {isEditing ? "Editar Feriado" : "Adicionar Feriado"}
          </DialogTitle>
          {isAutoGenerated && (
            <TooltipProvider>
              <Tooltip>
                <TooltipTrigger asChild>
                  <div className="inline-flex items-center">
                    <InfoIcon className="h-4 w-4 text-muted-foreground cursor-help" />
                  </div>
                </TooltipTrigger>
                <TooltipContent side="top" className="max-w-[240px] text-xs">
                  Este feriado foi gerado automaticamente e a data não pode ser alterada.
                </TooltipContent>
              </Tooltip>
            </TooltipProvider>
          )}
        </DialogHeader>
        <HolidayForm defaultValues={holiday} onCancel={handleCancel} />
      </DialogContent>
    </Dialog>
  );
};
