
import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Holiday } from "@/types/holiday";

export function useHolidaysByDate(date: string) {
  return useQuery({
    queryKey: ["holidays-by-date", date],
    queryFn: async () => {
      if (!date) return [];
      
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return [];
      
      const { data, error } = await supabase
        .from('holidays')
        .select('*')
        .eq('date', date)
        .eq('user_id', user.id)
        .eq('is_active', true);
      
      if (error) {
        console.error('Error fetching holidays by date:', error);
        return [];
      }
      
      return (data || []).map((item: any) => ({
        id: item.id,
        date: item.date,
        name: item.name,
        type: item.type,
        description: item.description || undefined,
        isActive: item.is_active,
        blockingType: item.blocking_type,
        customStartTime: item.custom_start_time || undefined,
        customEndTime: item.custom_end_time || undefined,
        autoGenerated: item.auto_generated || false,
        createdAt: item.created_at,
        updatedAt: item.updated_at
      })) as Holiday[];
    },
    enabled: !!date,
    staleTime: 1000 * 60 * 5, // 5 minutes
  });
}
