
export type BlockingType = 
  | 'full_day'    // Bloqueia o dia inteiro
  | 'morning'     // Bloqueia até 12:00
  | 'afternoon'   // Bloqueia depois das 12:00
  | 'custom';     // Bloqueia em horário personalizado

export interface Holiday {
  id: string;
  date: string; // formato: "yyyy-MM-dd"
  name: string;
  type: HolidayType;
  description?: string;
  isActive: boolean;
  blockingType: BlockingType;
  customStartTime?: string;
  customEndTime?: string;
  autoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

export type HolidayType = 
  | 'national'  // Feriado nacional
  | 'state'     // Feriado estadual
  | 'municipal' // Feriado municipal
  | 'custom';   // Feriado personalizado

export interface HolidayFormData {
  date: Date;
  name: string;
  type: HolidayType;
  description?: string;
  isActive: boolean;
  blockingType?: BlockingType;
  customStartTime?: string;
  customEndTime?: string;
}
